act: relu
alpha:
- 5e-2
- 1e-2
- 5e-1
- 1
- 5
- 1e1
- 5e1
bias: true
hidden_layers: 2
iters: 8000
linearize: false
lr: 1e-4
save_every: 20
width: 100
xdata:
- - -2
  - 0.5
ydata:
- - 3
  - -1.0
zero_output: true
